version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            # The line below mounts the project directory to the container's workDir.
            # This allows live updates to the code inside the container without rebuilding the image.
            # It's useful during development, as the Dockerfile only copies the code during the image build.
            - .:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./moz:/var/www/html/public
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api
            MYSQL_USER: user
            MYSQL_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

volumes:
    dbdata:

networks:
    app-network:
        driver: bridge
